### ISSUE TITLE
Incoherencias de horarios de pases en la guía

### ISSUE THREAD

**Issue by kralizeck** [kralizeck/tvhstar-parche-epg#2]
Viendo que algunas cosas que programé grababan lo que no era (siempre de madrugada) y después de comparar lo que exporta movistar en xml, txt y word, con la guía online (p.ej. natgw: http://www.movistarplus.es/programacion-tv/2018-08-27/NATGW), he llegao a la conclusión que el aparente "desorden" en el xml entre un día y el siguiente no es tal, en realidad es una lógica muy particular de movistar... a ver si soy capaz de explicarme...

Parece que ellos empiezan la programación de un día a partir de las 06:00 y termina con el pase que haya antes de la 06:00 del día siguiente... PEEEROOO, y aquí viene lo puñetero, en las exportaciones ponen como fecha de ese rango de pases las del día del pase inicial de las 06:00 y, claro, todos los pases después de las 00:00 (que ya deberían aparecer en la exportación como del día siguiente) aparecen con el mismo día.

Lo que yo interpreté como desorden, es un "orden" estilo movistar...

En un rato me pelearé con el script .js que reordenaba los pases, a ver si es fácil de resolver.

**Comment by gedas07** [comment]
gracias por avisar
otra cosa por ejemplo en tele 5 esta noche a las  22:00 daban the gooddoctor creo , y en la exportacion para el tvheadend salia programa por determinar 
Alguna forma de arreglarlo?
Aunque creo que eso es lo que envia la pagina de descarga

**Comment by kralizeck** [comment]
> Aunque creo que eso es lo que envia la pagina de descarga

Pues sí. Acabo de hacer una exportación desde la web y es lo que envía movistar.
Tendrías que ver cómo configurar otros proveedores de guía para complementar esas cadenas. Por si no lo has mirado, @LuisPalacios tiene una web explicando cómo usar [Webgrab+](http://www.luispa.com/archivos/1587), que él lo usaba para complementar algunas cadenas.
Yo lo miré por encima y de lejos... no era algo que me interesara/necesitara.

Ya resolví el asunto de cambiar las fechas. En un rato publico los nuevos ficheros.

**Comment by kralizeck** [comment]
Ya está subida la nueva versión y documentada la [actualización](https://github.com/kralizeck/tvhstar-parche-epg#algunos-archivos-sueltos-no-necesarios-para-el-uso-del-script).
Avisa si falla algo.
Saludos.

**Comment by gedas07** [comment]
muchas gracias
En cuanto pueda los pruebo que ahora estoy liado con una rock64 je je

**Comment by gedas07** [comment]
Probado y funciona perfectamente.
Lo que no he mirado si los pases de la noche estan correctos..........   :(

**Comment by kralizeck** [comment]
Lo doy por resuelto... hasta que los de movistar la vuelvan a liar... ;P
