### ISSUE TITLE
Problemas con canales exportados 

### ISSUE THREAD

**Issue by gedas07** [kralizeck/tvhstar-parche-epg#3]
Hola 
Necesito de tu ayuda otra vez .
He puesto los canales que yo necesito exportar para tvheadend en CadenasHOME con true, uno de ellos es el liga de Campeones que lo he añadido por que no estaba , en tu data.txt si que esta. , tambien he pedido con true  el Toros y un par mas que estos si que estaban .
He hecho sudo npm run build , me da ok 
y luego sudo ./parche-epg.hs 7 y me da ok , 
Yo he puesto para que me de el EPG de 22 canales , pero el parche-epg saca el epg de todos , perfecto, pero cuando se termina el proceso del parche-epg la parte que hace el script tvhstar.sh "sudo npm run start" me dice lo siguiente
Hecho!! - 87 canales y 19300 pases
Fin de ejecucion

y no me exporta a tvheadend , esos canales que yo quiero liga, toros etc.....
tvheadend con el tv_grab me reconoce esos 87 canales , pero no parte de mis 22 pedidos 

En los temporales si que los descarga bien en los archivos guia.movistar-xml.xml y en guia.movistar-xml.json,    si que estan los canales que yo pido, pero en el archivo guia.movistar-xmltv.json ya no estan.
Y en el archivo final guia.xml , ni rastro de ellos solo esos 87 canales 
He estado mirando a ver  si veia como hacerlo , pero no he sabido.

**Comment by kralizeck** [comment]
Hola.
Si están en los dos primeros temporales es que tvhstar sí los empieza a procesar, pero si en el último temporal (xmltv.json) ya no están... pienso que alguna incoherencia tiene que haber entre los nombres/id en CadenasHOME y lo que exporta movistar... revisa bien los nombres y las instrucciones de configuración de tvhstar.

Pega por aquí tu configuración en CadenasHOME de uno de esos canales que no se procesan y también el guia.movistar-xml.xml, a ver si veo "algo".

Saludos.

**Comment by gedas07** [comment]
Muchas gracias , por la ayuda de nuevo ,
Ya lo he solucionado gracias a ti , lo ponia todo bien pero en nombre movistar ponia HD y por eso no lo cogia.

**Comment by kralizeck** [comment]
De nada.
Encantao de ayudar.
