### ISSUE TITLE
Sin programación en canal #Vamos

### ISSUE THREAD

**Issue by Sockolet** [kralizeck/tvhstar-parche-epg#4]
Hola. Desde que comencé a utilizar el parche sobre tvhstar he detectado que nunca se lista la programación del canal #Vamos. Ni siquiera sale listado en la guia temporal que se exporta de la página de M antes de pasarle el script de formato.

¿Estoy haciendo algo mal?

**Comment by kralizeck** [comment]
No, no estás haciendo nada mal. Movistar ha añadido ese canal y eliminado un par de ellos.

Ya está resuelto.
Ya está el data.txt con las modificaciones: añadido VAMOSD, eliminados CPD2 y ARTHUR.
Por lo que he visto también han cambiado los diales de varios canales, pero eso ya es cosa de modificar en el src/canalesHOME.js de tvhstar.

**Comment by kralizeck** [comment]
Hola.
No estás haciendo nada mal.
Son cambios recientes de movi en los canales.
Hay que revisar algunos ficheros.

Saludos.

**Comment by Sockolet** [comment]
Funciona perfectamente :D 
gracias @kralizeck !!

**Comment by kralizeck** [comment]
Muy bien.

Saludos.
